Add pipeline item for updating the Algolia search index
This isn't complete, and I need help from @tboerger with the secrets,
but I think it should form the basis of the pipeline item for updating
the search index hosted with Algolia. I think it will at least need to
figure out how to handle the output at the end of the docsearch-scraper
process that asks:

Do you want to update the nb_hits in /opt/docsearch-scraper/owncloud.json ? [y/n]:

Currently, when running from the command-line, it results in the
following error (which I've taken up with Algolia support):

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/src/index.py", line 98, in <module>
    run_config(environ['CONFIG'])
  File "/root/src/index.py", line 87, in run_config
    config.update_nb_hits(DocumentationSpider.NB_INDEXED)
  File "src/config/config_loader.py", line 135, in update_nb_hits
    nb_hit_updater.update()
  File "src/config/nb_hits_updater.py", line 24, in update
    'Do you want to update the nb_hits in ' + self.config_file + ' ?'):
  File "src/helpers.py", line 10, in confirm
    ans = input(prompt)
EOFError: EOF when reading a line